export function unexpectedSuccess() {
  return assert.fail(null, null, 'Unexpected success');
}
